### PR TITLE
Find DIA SDK independent from the version of Visual Studio 

### PR DESCRIPTION
**Pull request by danielfenner**
Implement some trivial trial and error logic to guess the path.

### CODE REVIEW

**Comment by danielfenner** [comment]
The solution is a bit ugly. I'm very open to suggestions ...

**Comment by pierricgimmig** [comment]
I'm happy with that solution to be honest.  @beckerhe do you think it's a good compromise?  For reference, we had discussed the issue in https://github.com/pierricgimmig/orbitprofiler/issues/127.

This is definitely an improvement to the current situation and will work in the majority of cases.  If a user has custom install path for VS, then it's on them to modify the toolchain file.

**Comment by beckerhe** [comment]
Hi both of you,
I couldn't let go of this problem yesterday evening, so I dived into the cmake source code.
And I found a cmake variable which contains the path to the currenlty used instance of visual
studio. It's called CMAKE_GENERATOR_INSTANCE and it was introduced pretty recently in version 3.15 (which we require anyway), that's why there is almost no documentation out there about it.

I'm currently preparing a branch with a solution based on this variable. It's almost done, I just wanna do a fresh build, which takes some time. When it's done, I will create a pull request and we can debate the pros and cons of these two ways.

**Comment by pierricgimmig** [comment]
> I couldn't let go of this problem yesterday evening, so I dived into the cmake source code.

I like your style Henning!!  Thanks a lot for looking into this and coming up with a clean solution!  Cheers!

**Pull request closed without merging**
