### PR TITLE
Remove check for update function

### PR DESCRIPTION
**Pull request by dimitry-**
This needs to be moved elsewhere. The main reason for removing it is to
untie the project from libcurl.so.

### CODE REVIEW

**Comment by pierricgimmig** [comment]
Could an option be to package the .so that was use at build time?  Or could we perhaps link statically?

**Comment by dimitry-** [comment]
I think the better way is to split App class to stop depending on UI things so that Service does not use OrbitVersion, which seems like something worth doing anyways.

**Comment by pierricgimmig** [comment]
The service could potentially need to check for version too.  Also, we could potentially run the UI on a remote instance and stream the framebuffer to a browser.

Do you have a workaround that would allow us to keep the dependency to libcurl?

**Comment by dimitry-** [comment]
Since the Service (normally) does not communicate with user, I do not think there is value in checking it on the service side - it should probably be an additional check from the gui (getting service version and displaying message if it needs to be updated).. but yes - we can just statically link libcurl to solve the problem with symbol versoins.

**Pull request closed without merging**
